package com.Mlh;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.Mlh.Callwebservice;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CallWebServiceImpService", targetNamespace = "http://Mlh.com/", wsdlLocation = "http://localhost:7879/call?wsdl")
public class CallWebServiceImpService
    extends Service
{

    private final static URL CALLWEBSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALLWEBSERVICEIMPSERVICE_EXCEPTION;
    private final static QName CALLWEBSERVICEIMPSERVICE_QNAME = new QName("http://Mlh.com/", "CallWebServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7879/call?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALLWEBSERVICEIMPSERVICE_WSDL_LOCATION = url;
        CALLWEBSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public CallWebServiceImpService() {
        super(__getWsdlLocation(), CALLWEBSERVICEIMPSERVICE_QNAME);
    }

    public CallWebServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALLWEBSERVICEIMPSERVICE_QNAME, features);
    }

    public CallWebServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, CALLWEBSERVICEIMPSERVICE_QNAME);
    }

    public CallWebServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALLWEBSERVICEIMPSERVICE_QNAME, features);
    }

    public CallWebServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CallWebServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Callwebservice
     */
    @WebEndpoint(name = "CallWebServiceImpPort")
    public Callwebservice getCallWebServiceImpPort() {
        return super.getPort(new QName("http://Mlh.com/", "CallWebServiceImpPort"), Callwebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Callwebservice
     */
    @WebEndpoint(name = "CallWebServiceImpPort")
    public Callwebservice getCallWebServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Mlh.com/", "CallWebServiceImpPort"), Callwebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALLWEBSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw CALLWEBSERVICEIMPSERVICE_EXCEPTION;
        }
        return CALLWEBSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
