package com.Mlh;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "callwebservice", targetNamespace = "http://Mlh.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Callwebservice {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Mlh.com/callwebservice/myRequest", output = "http://Mlh.com/callwebservice/myResponse")
    public String my();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Mlh.com/callwebservice/checkUserImageRequest", output = "http://Mlh.com/callwebservice/checkUserImageResponse")
    public int checkUserImage(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        byte[] arg1);

}
